improved check_java, added summary, prettified outputs

diff --git a/codecrunch/check_java b/codecrunch/check_java
--- a/codecrunch/check_java
+++ b/codecrunch/check_java
@@ -2,35 +2,48 @@
 cd . 
 if [ -z "$1" ]
 then
-    echo "Problem name is required as the first argument."
-    echo "eg: ./check.sh Helloworld"
-    exit 0
-    
+	echo "Problem name is required as the first argument."
+	echo "eg: ./check.sh Helloworld"
+	exit 0
+
 fi
-problem="$1"    #problem name as first variable
+problem="$1"
+problem=${problem/.java}
+#problem name as first variable
 
 #compiling .java file
 if ! javac $problem.java;
 then
-    echo "Compilation Failed"
-    exit 0;
+	echo "Compilation Failed"
+	exit 0;
 else
-    echo "Compiled $problem.java successfully"
+	echo "Compiled $problem.java successfully"
 fi
 
 #enumerate all .in files in the same directory
+correct_count=0
+total_count=0
 for i in ./input/*.in
 do
-		tc_name=${i:8}
-		tc_name=${tc_name#.in}
-    java $problem < $i > ${i/.in/.o}
-    results=$( diff ${i/.in/.o} ./output/${tc_name/.in/.out} > ${i/.in/.diff})
-    if [ $? -eq 0 ]     #check if there is a difference between the two files
-    then
-        echo ${i/.in}": Correct"
-        rm ${i/.in/.o} ${i/.in/.diff}
-    else
-        echo ${i/.in}": Incorrect"
-        echo "Output in ${i/.in/.o}, diff in ${i/.in/.diff} (< your output | > official output)"
-    fi
+	tc_name=${i:8}
+	tc_name_len=${#tc_name}
+	let "tc_name_len -= 3"
+	tc_name=${tc_name:0:$tc_name_len}
+	tc_num=${tc_name:(-1)}
+	java $problem < $i > ${i/.in/.o}
+
+	let "total_count+=1"
+	results=$( diff ${i/.in/.o} ./output/"$tc_name.out" > ${i/.in/.diff})
+	if [ $? -eq 0 ]     #check if there is a difference between the two files
+	then
+		echo "Test Case $tc_num: Correct"
+		rm ${i/.in/.o} ${i/.in/.diff}
+		let "correct_count+=1"
+	else
+		echo
+		echo "Test case $tc_num: Incorrect"
+		cat ${i/.in/.diff} 
+		echo
+	fi
 done
+echo "End of judging. $correct_count correct out of $total_count."
